### PR TITLE
feat: add secrets, add cert creation, make optional

### PR DESCRIPTION
**Pull request by JasonPowr**
Pr to allow the operator to either create and use certs, or use certs created by user.

## Testing without cert and secrets
1. Launch and authenticate with cluster
2. Install Keycloak on the cluster
   1. `oc create -k https://github.com/securesign/sigstore-ocp/keycloak/operator/base`
   2. `oc create -k https://github.com/securesign/sigstore-ocp/keycloak/resources/base`
3. Run the operator
   1. `make install && make run` 
4. Add keycloak url to `config/samples/rhtas_v1alpha1_securesign.yaml`
5. Create a namespace: `oc new-project securesign`
6. Apply the yaml file: `oc apply -f config/samples/rhtas_v1alpha1_securesign_cert_create.yaml -n securesign`
7. Sign and verify

## Testing with cert and secrets
1. As Above (1-5)
2. Create secrets in namespace
 ``` 
oc -n securesign create secret generic fulcio-secret-rh --from-file=private=file_ca_key.pem --from-file=public=file_ca_pub.pem --from-file=cert=fulcio-root.pem --from-literal=password=secure  && oc -n securesign create secret generic rekor-private-key --from-file=private=rekor_key.pem
  ```
3. Apply the yaml file: `oc apply -f config/samples/rhtas_v1alpha1_securesign.yaml -n securesign`
4. Sign and verify

Completes https://github.com/securesign/secure-sign-operator/issues/1

### CODE REVIEW

**Comment by cooktheryan** [comment]
@JasonPowr will the certificate creation work at all for Kind clusters?


We may need to reset the config/sample deployment and then create an additional config/sample for certificate creation and to make sure CI is happy because it can only use kind

**Comment by JasonPowr** [comment]
@cooktheryan I believe secret creation should work for the kind cluster at least I cant see why it wouldn't off the top of my  head, I see what you mean though, let me take a look and see :)

**Comment by JasonPowr** [comment]
@cooktheryan that should keep the ci happy :) 

```
Run sleep 120
NAME                                 READY   STATUS      RESTARTS   AGE
create-config-z2qd7                  0/1     Completed   0          2m
create-tree-rekor-kpgqm              0/1     Completed   0          2m
create-tree-xsrmm                    0/1     Completed   0          2m
ctlog-6fcb68984b-4g4fw               1/1     Running     0          2m
fulcio-server-7c67f996d5-v7kgn       1/1     Running     0          2m
rekor-redis-fff7cf654-7t7pd          1/1     Running     0          2m
rekor-server-7cc5dc7b55-z5bq9        1/1     Running     0          2m
trillian-db-55d446f549-lfpmr         1/1     Running     0          2m
trillian-logserver-9856ccddd-4bb6l   1/1     Running     0          2m
trillian-logsigner-cb9d88cdd-422ft   1/1     Running     0          2m
```

I think it would be a good idea to test both cert creation and using your own WDYT?

**Comment by cooktheryan** [comment]
@JasonPowr completely agree having both tests will save our butts at the end of the day. 

@JasonPowr why don't we file an issue to test for both. It will be a good opportunity for us to finish the work of allowing multiple installations of securesign deployed in namespaces.

**Review by cooktheryan — APPROVED** [review]

**Pull request merged**
