### PR TITLE
feat: pass proxy configuration to operands

### PR DESCRIPTION
**Pull request by miyunari**
jira: https://issues.redhat.com/browse/SECURESIGN-1038

### CODE REVIEW

**Comment by miyunari** [comment]
Hi @osmman - thanks for your review. Do you know what is going on with the ci pipeline tests?

**Comment by osmman** [comment]
> Hi @osmman - thanks for your review. Do you know what is going on with the ci pipeline tests?

Hi, problem is that PR is from forked repository so Github action do not enable to access to CI's secrets. Current solution is to create new PR from current securesign/secure-sign-operator repo.

**Comment by miyunari** [comment]
> > Hi @osmman - thanks for your review. Do you know what is going on with the ci pipeline tests?
> 
> Hi, problem is that PR is from forked repository so Github action do not enable to access to CI's secrets. Current solution is to create new PR from current securesign/secure-sign-operator repo.

Ah ok, thanks for explaining @osmman  :smiley:  Does this mean I have to create a new branch or can this be merged anyway? :slightly_smiling_face:

**Comment by osmman** [comment]
> > > Hi @osmman - thanks for your review. Do you know what is going on with the ci pipeline tests?
> > 
> > 
> > Hi, problem is that PR is from forked repository so Github action do not enable to access to CI's secrets. Current solution is to create new PR from current securesign/secure-sign-operator repo.
> 
> Ah ok, thanks for explaining @osmman 😃 Does this mean I have to create a new branch or can this be merged anyway? 🙂

Please create a new branch, Kind deployment and upgrade operator contains most of our e2e tests.

**Comment by miyunari** [comment]
Ok :)

**Pull request closed without merging**
