### PR TITLE
adding annotations to csv for Operator infrastructure feature test

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
These were added according to the docs ([Operator infrastructure feature test](https://docs.engineering.redhat.com/display/CVP/Operator+Verification+Pipeline+Documentation#operator-infrastructure-feature-test)) shared by Konflux team.
/cc @cooktheryan 
/cc @lance

### CODE REVIEW

**Review by cooktheryan — APPROVED** [review]
LGTM

**Comment by cooktheryan** [comment]
@Gregory-Pereira we should file issues on each of these to figure out what would be required to make them true

**Comment by Gregory-Pereira** [comment]
> @Gregory-Pereira we should file issues on each of these to figure out what would be required to make them true

will do.

**Comment by Gregory-Pereira** [comment]
These changes were attempted to follow the docs here: https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/proc_maintaining_operator_graphs/

**Pull request merged**
