### PR TITLE
Split Client server into two images

### PR DESCRIPTION
**Pull request by JasonPowr**
This pr makes the necessary changes to the client sever, after the split one contains cosign and gitsign the other contains rekor-cli and ec

### CODE REVIEW

**Comment by bouskaJ** [comment]
@JasonPowr I don't like the concept of having two pods at all TBH. I know you have reason to do that so I am thinking about having both container running in the single pod. That would need containers to serve on different port. Would it be possible to configure it using ENV variable or so?

**Comment by JasonPowr** [comment]
> @JasonPowr I don't like the concept of having two pods at all TBH. I know you have reason to do that so I am thinking about having both container running in the single pod. That would need containers to serve on different port. Would it be possible to configure it using ENV variable or so?

I agree its not the nicest solution, I'm not sure if I can configure it using a Env var but ill look into it. The main reason for the separate pods is because Apache web sever automatically binds to port 8080 by default, and when running the two images in the same pod it results in a port binding error

**Comment by cooktheryan** [comment]
@JasonPowr stepping back what is the why? To make the change

**Comment by JasonPowr** [comment]
> @JasonPowr stepping back what is the why? To make the change

@cooktheryan I believe its because the client server image got too big during TP2 and was breaking builds: https://issues.redhat.com/browse/SECURESIGN-624

**Comment by JasonPowr** [comment]
@bouskaJ So I don't think there is a way I can set it up using env vars, If we don't want it running two pods I believe we may have two options

We could do something like this:
```
Containers: []core.Container{
	{
		Name:            cliServerName,
		Image:           image,
		ImagePullPolicy: "IfNotPresent",
		Ports: []core.ContainerPort{
			{
				ContainerPort: 8080,
				Protocol:      "TCP",
			},
		},
		Command: []string{"/bin/sh", "-c"},
		Args: []string{
			"sed -i 's/Listen 0.0.0.0:8080/Listen 0.0.0.0:8081/' /etc/httpd/conf/httpd.conf && run-httpd",
		},
	},
},
```

Or we could move the sed command to the build process of the second client server image, wdyt?

**Comment by lance** [comment]
> > @JasonPowr stepping back what is the why? To make the change
> 
> @cooktheryan I believe its because the client server image got too big during TP2 and was breaking builds: https://issues.redhat.com/browse/SECURESIGN-624

Yes - it's not the image itself, but the `source-image-build` task results are too large for konflux. This is because it was including all of the source for cosign, gitsign, rekor-cli and ec. Once we added ec to the mix it went over the task result size limit, and that was not something easily fixable by the konflux team iiuc.

**Comment by lance** [comment]
> We could do something like this:
> 
> ```
> Containers: []core.Container{
> 	{
> 		Name:            cliServerName,
> 		Image:           image,
> 		ImagePullPolicy: "IfNotPresent",
> 		Ports: []core.ContainerPort{
> 			{
> 				ContainerPort: 8080,
> 				Protocol:      "TCP",
> 			},
> 		},
> 		Command: []string{"/bin/sh", "-c"},
> 		Args: []string{
> 			"sed -i 's/Listen 0.0.0.0:8080/Listen 0.0.0.0:8081/' /etc/httpd/conf/httpd.conf && run-httpd",
> 		},
> 	},
> },
> ```
> 
> Or we could move the sed command to the build process of the second client server image, wdyt?

IMO the container should default to 8080. The reason we are having to do all of these shenanigans is because we want both servers to run from the same pod. So I think having the `sed` command to hack the port here in the Container command args is the right place for it. Don't forget to set `ContainerPort` to 8081 on that Container spec too.

**Comment by bouskaJ** [comment]
> > We could do something like this:
> > ```
> > Containers: []core.Container{
> > 	{
> > 		Name:            cliServerName,
> > 		Image:           image,
> > 		ImagePullPolicy: "IfNotPresent",
> > 		Ports: []core.ContainerPort{
> > 			{
> > 				ContainerPort: 8080,
> > 				Protocol:      "TCP",
> > 			},
> > 		},
> > 		Command: []string{"/bin/sh", "-c"},
> > 		Args: []string{
> > 			"sed -i 's/Listen 0.0.0.0:8080/Listen 0.0.0.0:8081/' /etc/httpd/conf/httpd.conf && run-httpd",
> > 		},
> > 	},
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or we could move the sed command to the build process of the second client server image, wdyt?
> 
> IMO the container should default to 8080. The reason we are having to do all of these shenanigans is because we want both servers to run from the same pod. So I think having the `sed` command to hack the port here in the Container command args is the right place for it. Don't forget to set `ContainerPort` to 8081 on that Container spec too.

yes, I agree with @lance I would not hack the container image. I still think that having both in one pod (including the hack) is less messy than having two deployments but let's hear from others @osmman @cooktheryan WDYT?

**Comment by osmman** [comment]
> > > We could do something like this:
> > > ```
> > > Containers: []core.Container{
> > > 	{
> > > 		Name:            cliServerName,
> > > 		Image:           image,
> > > 		ImagePullPolicy: "IfNotPresent",
> > > 		Ports: []core.ContainerPort{
> > > 			{
> > > 				ContainerPort: 8080,
> > > 				Protocol:      "TCP",
> > > 			},
> > > 		},
> > > 		Command: []string{"/bin/sh", "-c"},
> > > 		Args: []string{
> > > 			"sed -i 's/Listen 0.0.0.0:8080/Listen 0.0.0.0:8081/' /etc/httpd/conf/httpd.conf && run-httpd",
> > > 		},
> > > 	},
> > > },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Or we could move the sed command to the build process of the second client server image, wdyt?
> > 
> > 
> > IMO the container should default to 8080. The reason we are having to do all of these shenanigans is because we want both servers to run from the same pod. So I think having the `sed` command to hack the port here in the Container command args is the right place for it. Don't forget to set `ContainerPort` to 8081 on that Container spec too.
> 
> yes, I agree with @lance I would not hack the container image. I still think that having both in one pod (including the hack) is less messy than having two deployments but let's hear from others @osmman @cooktheryan WDYT?

Did you think about usage of sidecars? Basically to have one containers with HTTP server and sidecars with binaries

**Comment by bouskaJ** [comment]
> > > > We could do something like this:
> > > > ```
> > > > Containers: []core.Container{
> > > > 	{
> > > > 		Name:            cliServerName,
> > > > 		Image:           image,
> > > > 		ImagePullPolicy: "IfNotPresent",
> > > > 		Ports: []core.ContainerPort{
> > > > 			{
> > > > 				ContainerPort: 8080,
> > > > 				Protocol:      "TCP",
> > > > 			},
> > > > 		},
> > > > 		Command: []string{"/bin/sh", "-c"},
> > > > 		Args: []string{
> > > > 			"sed -i 's/Listen 0.0.0.0:8080/Listen 0.0.0.0:8081/' /etc/httpd/conf/httpd.conf && run-httpd",
> > > > 		},
> > > > 	},
> > > > },
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Or we could move the sed command to the build process of the second client server image, wdyt?
> > > 
> > > 
> > > IMO the container should default to 8080. The reason we are having to do all of these shenanigans is because we want both servers to run from the same pod. So I think having the `sed` command to hack the port here in the Container command args is the right place for it. Don't forget to set `ContainerPort` to 8081 on that Container spec too.
> > 
> > 
> > yes, I agree with @lance I would not hack the container image. I still think that having both in one pod (including the hack) is less messy than having two deployments but let's hear from others @osmman @cooktheryan WDYT?
> 
> Did you think about usage of sidecars? Basically to have one containers with HTTP server and sidecars with binaries

Good idea @osmman I like it! Here is a nice example with nginx server https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

**Comment by cooktheryan** [comment]
I would like to see if there is any way to fix this in Konflux. This seems wrong and something more folks are going to face in the future.

**Comment by cooktheryan** [comment]
+1 @osmman idea that would be a very smooth way to solve this

**Comment by JasonPowr** [comment]
@bouskaJ @osmman So to do this Ill need to make changes to the client-server images and remove the HTTP aspects of them, before I begin the process are you looking for something like this or am I misunderstanding?

```
Spec: core.PodSpec{
	Volumes: []core.Volume{
		{
			Name: "shared-data",
			VolumeSource: core.VolumeSource{
				EmptyDir: &core.EmptyDirVolumeSource{},
			},
		},
	},
	InitContainers: []core.Container{
		{
			Name:    "init-shared-data-cg",
			Image:   "quay.io/japower/client_server_test:latest",
			Command: []string{"sh", "-c", "cp -r /opt/app-root/src/clients/* /var/www/html/clients/"},
			VolumeMounts: []core.VolumeMount{
				{
					Name:      "shared-data",
					MountPath: "/var/www/html/clients/",
				},
			},
		},
		{
			Name:    "init-shared-data-re",
			Image:   "quay.io/japower/client_server_test_re:latest",
			Command: []string{"sh", "-c", "cp -r /opt/app-root/src/clients/* /var/www/html/clients/"},
			VolumeMounts: []core.VolumeMount{
				{
					Name:      "shared-data",
					MountPath: "/var/www/html/clients/",
				},
			},
		},
	},
	Containers: []core.Container{
		{
			Name:            cliServerName,
			Image:           "registry.access.redhat.com/ubi9/httpd-24@sha256:965f7b03ae8f45228bad765ce47bc8956711e854213df0e4cee8623d51317b0a",
			ImagePullPolicy: core.PullAlways,
			Ports: []core.ContainerPort{
				{
					ContainerPort: 8080,
					Protocol:      core.ProtocolTCP,
				},
			},
			VolumeMounts: []core.VolumeMount{
				{
					Name:      "shared-data",
					MountPath: "/var/www/html/clients/",
				},
			},
		},
	},
},
```

**Comment by cooktheryan** [comment]
this is a very smooth implementation of this idea +1

**Review by osmman — APPROVED** [review]

**Pull request merged**
