### PR TITLE
[SECURESIGN-957] Change Deployment strategy to Recreate for services with PVCs

### PR DESCRIPTION
**Pull request by bouskaJ**

### CODE REVIEW

**Comment by bouskaJ** [comment]
Getting 
```
          message: 'rpc error: code = Unknown desc = failed to pull and unpack image
            "quay.io/redhat-user-workloads/rhtas-tenant/rekor-search-ui/rekor-search-ui@sha256:03fa0d23079aa4146d6d7b3f4edaa302e383e7d0a6c15cbf73a58179f1d07e02":
            failed to extract layer sha256:b5ccc9e428274d607f3a994cb9c15b03dac782db2474851f30fb07861cc94ba9:
            write /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/324/fs/opt/app-root/src/node_modules/@patternfly/react-tokens/dist/esm/c_expandable_section_m_limit_width__content_MaxWidth.js:
            no space left on device: unknown'
```
from the upgrade CI. Please don't pay attention to that workflow (I will investigate how to cleanup memory)

**Comment by bouskaJ** [comment]
> Getting
> 
> ```
>           message: 'rpc error: code = Unknown desc = failed to pull and unpack image
>             "quay.io/redhat-user-workloads/rhtas-tenant/rekor-search-ui/rekor-search-ui@sha256:03fa0d23079aa4146d6d7b3f4edaa302e383e7d0a6c15cbf73a58179f1d07e02":
>             failed to extract layer sha256:b5ccc9e428274d607f3a994cb9c15b03dac782db2474851f30fb07861cc94ba9:
>             write /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/324/fs/opt/app-root/src/node_modules/@patternfly/react-tokens/dist/esm/c_expandable_section_m_limit_width__content_MaxWidth.js:
>             no space left on device: unknown'
> ```
> 
> from the upgrade CI. Please don't pay attention to that workflow (I will investigate how to cleanup memory)

Fix https://github.com/securesign/secure-sign-operator/pull/378

**Comment by JasonPowr** [comment]
Thanks to some help from @osmman I was able to properly reproduce the issue by having 1.0.0 installed in one node, I then marked that node as unschedulable so the upgrade would install on a new node, trillian seemed fine but rekor got stuck in a pending state, with this error

```
0/6 nodes are available: 1 node(s) had volume node affinity conflict, 2 node(s) were unschedulable, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/6 nodes are available: 6 Preemption is not helpful for scheduling..
``` 
https://medium.com/@golusstyle/resolving-the-volume-node-affinity-conflict-error-in-kubernetes-e1a906ad8ea8

In this case, Rekor and trillian got scheduled, on two different nodes so I had to disable two out of the three.

**Comment by bouskaJ** [comment]
I guess it is the cluster configuration error there is no node to schedule the pod:

-  you have 3 master nodes (they are not used for workload) 
- 2 nodes unschedulable (you probably disable them) 
- 1 node with volume conflict that is described on link you provided https://medium.com/@golusstyle/resolving-the-volume-node-affinity-conflict-error-in-kubernetes-e1a906ad8ea8

**Review by JasonPowr — APPROVED** [review]
/lgtm

**Pull request merged**
