### PR TITLE
catalog: remove alpha channel, add rhtas-1-0

### PR DESCRIPTION
**Pull request by lance**
This commit removes the alpha channel from the existing fbcs, replacing it with an rhtas-1-0 channel to be used for all updates to the 1.0.x release line.

Fixes [SECURESIGN-881](https://issues.redhat.com//browse/SECURESIGN-881)

### CODE REVIEW

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Review by Gregory-Pereira — APPROVED** [review]

**Comment by JasonPowr** [comment]
Looks fine to me :), but I'd say we can remove the bundle from the graph files here, and in 4.14 and 4.15
https://github.com/securesign/secure-sign-operator/pull/357/files#diff-7e25bcdfb0672eddc760c5f3cca0b6ea575089702f04347681a04939c02a8ed0R21-R24

Unless we want to keep them as some sort of record/history?

**Review by JasonPowr — APPROVED** [review]
/lgtm

**Pull request merged**
