### PR TITLE
SECURESIGN-842 | Operator's metrics are not consumed by OCP monitor

### PR DESCRIPTION
**Pull request by JasonPowr**
# Testing 
To test this, you just need to build and deploy the operator, you should see a new target being created under `Observe -> Targets` called `rhtas-operator-controller-manager-metrics-monitor`, you should then be able to query the metrics of the operator.

### CODE REVIEW

**Comment by JasonPowr** [comment]
@osmman @bouskaJ Quick question, I have been thinking about this a bit, like with the ci we needed to install Prometheus prior to installing the operator so it has a definition of the service monitor type, will this cause an issue? I believe it will, as it would fail to install on clusters without an install of Prometheus.

Instead should this be tied to the securesign resource, as in:
```
spec:
  monitoring:
    enabled: true
  rekor:
    externalAccess:
    ......
``` 
then if enabled create the service monitors, service etc ?

**Comment by osmman** [comment]
> @osmman @bouskaJ Quick question, I have been thinking about this a bit, like with the ci we needed to install Prometheus prior to installing the operator so it has a definition of the service monitor type, will this cause an issue? I believe it will, as it would fail to install on clusters without an install of Prometheus.
> 
> Instead should this be tied to the securesign resource, as in:
> 
> ```
> spec:
>   monitoring:
>     enabled: true
>   rekor:
>     externalAccess:
>     ......
> ```
> 
> then if enabled create the service monitors, service etc ?

I think that at this moment we can live with it, for example a lot of operators depends on cert-manager to make their admission webhooks to work correctly. So unfortunatly right not it is prerequisity. Definatly it will be prefered to make it optional.

/lgtm

**Comment by JasonPowr** [comment]
@osmman Can I get another /lgtm pls :)

**Review by osmman — APPROVED** [review]

**Pull request merged**
