### PR TITLE
[SECURESIGN-1529] Keep url status up-to-date backport release-1.1

### PR DESCRIPTION
**Pull request by bouskaJ**

### CODE REVIEW

**Review by JasonPowr — APPROVED** [review]

**Comment by bouskaJ** [comment]
/override operator-v1-1-enterprise-contract / rhtas-operator-v1-1

**Comment by bouskaJ** [comment]
/override Red Hat Konflux / operator-v1-1-enterprise-contract / rhtas-operator-v1-1

**Comment by bouskaJ** [comment]
/override Red Hat Konflux/operator-v1-1-enterprise-contract/rhtas-operator-v1-1

**Comment by bouskaJ** [comment]
/override "Red Hat Konflux / operator-v1-1-enterprise-contract / rhtas-operator-v1-1"

**Pull request merged**
